"""Story-scoped triggers + use_only_own_triggers flag.

Этап 6.6 (Story Engine): триггеры можно привязать к конкретному сюжету,
чтобы не засорять глобальный namespace. Сюжет может работать с тремя
комбинациями:

- ``use_only_own_triggers=False`` (default, обратная совместимость) →
  CueListEditor показывает свои + global триггеры (story_id IS NULL).
- ``use_only_own_triggers=True`` → только свои (story_id == this story.id).
- Глобальные триггеры (``story_id IS NULL``) остаются доступными всем
  сюжетам как раньше — старые триггеры не ломаются.

Slug-уникальность:
- Был глобальный UNIQUE(slug) → теперь:
  * partial unique ``WHERE story_id IS NULL`` — два глобальных не
    создашь с одним slug.
  * partial unique ``(story_id, slug) WHERE story_id IS NOT NULL`` —
    в одном сюжете нельзя дублировать slug, но в разных можно
    (foo/v1 и foo/v2 для разных сюжетов).
- Это позволяет иметь global ``mafia_intro`` И story-scoped
  ``mafia_intro`` в каком-то сюжете одновременно (resolver на runtime
  сначала смотрит scope, потом fallback на global).

Revision ID: 20260527_story_triggers
Revises: 20260527_session_story
Create Date: 2026-05-27
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = "20260527_story_triggers"
down_revision: Union[str, Sequence[str], None] = "20260527_session_story"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. stories.use_only_own_triggers — флаг ограничения scope.
    op.add_column(
        "stories",
        sa.Column(
            "use_only_own_triggers",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    # 2. narrator_triggers.story_id — nullable FK на stories.
    op.add_column(
        "narrator_triggers",
        sa.Column(
            "story_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        "fk_narrator_triggers_story_id",
        source_table="narrator_triggers",
        referent_table="stories",
        local_cols=["story_id"],
        remote_cols=["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        "ix_narrator_triggers_story_id",
        "narrator_triggers",
        ["story_id"],
        unique=False,
    )

    # 3. Снять глобальный UNIQUE(slug). Имя дефолтное (autogenerated by
    # PostgreSQL для UNIQUE-column в CREATE TABLE) — narrator_triggers_slug_key.
    op.drop_constraint(
        "narrator_triggers_slug_key", "narrator_triggers", type_="unique"
    )

    # 4. Partial unique indexes для нового scope-aware namespace.
    # Global scope: только один global trigger с данным slug.
    op.create_index(
        "uq_narrator_triggers_global_slug",
        "narrator_triggers",
        ["slug"],
        unique=True,
        postgresql_where=sa.text("story_id IS NULL"),
    )
    # Per-story scope: уникальность (story_id, slug) только для не-global.
    # NULL story_id обработан выше; здесь partial условие исключает их,
    # чтобы (NULL, 'foo') не вступали в conflict с глобальным slug='foo'.
    op.create_index(
        "uq_narrator_triggers_story_slug",
        "narrator_triggers",
        ["story_id", "slug"],
        unique=True,
        postgresql_where=sa.text("story_id IS NOT NULL"),
    )


def downgrade() -> None:
    # Откат: возвращаем глобальный unique slug. Если в БД уже есть
    # story-scoped дубликаты — downgrade упадёт (это правильно, нельзя
    # потерять данные молча).
    op.drop_index(
        "uq_narrator_triggers_story_slug", table_name="narrator_triggers"
    )
    op.drop_index(
        "uq_narrator_triggers_global_slug", table_name="narrator_triggers"
    )
    op.create_unique_constraint(
        "narrator_triggers_slug_key", "narrator_triggers", ["slug"]
    )

    op.drop_index(
        "ix_narrator_triggers_story_id", table_name="narrator_triggers"
    )
    op.drop_constraint(
        "fk_narrator_triggers_story_id",
        "narrator_triggers",
        type_="foreignkey",
    )
    op.drop_column("narrator_triggers", "story_id")

    op.drop_column("stories", "use_only_own_triggers")
